version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
